const TALENT_QUICK_BUTTON_ICONS = Object.freeze({
	'Alchimie': '⚗️',
	'Bekehren & Überzeugen': '🗣️',
	'Betören': '🌹',
	'Boote & Schiffe': '⛵',
	'Brett- & Glücksspiel': '🎲',
	'Einschüchtern': '😠',
	'Etikette': '🎩',
	'Fährtensuchen': '👣',
	'Fahrzeuge': '🛞',
	'Fesseln': '🪢',
	'Fischen & Angeln': '🎣',
	'Fliegen': '🪽',
	'Gassenwissen': '🏘️',
	'Gaukeleien': '🤹',
	'Geographie': '🗺️',
	'Geschichtswissen': '📜',
	'Götter & Kulte': '🛕',
	'Handel': '⚖️',
	'Heilkunde Gift': '☠️',
	'Heilkunde Krankheiten': '😷',
	'Heilkunde Seele': '💟',
	'Heilkunde Wunden': '🩹',
	'Holzbearbeitung': '🪵',
	'Klettern': '🧗',
	'Körperbeherrschung': '🤸',
	'Kraftakt': '💪',
	'Kriegskunst': '🛡️',
	'Lebensmittelbearbeitung': '🍞',
	'Lederbearbeitung': '🧥',
	'Magiekunde': '🔮',
	'Malen & Zeichnen': '🖌️',
	'Mechanik': '⚙️',
	'Menschenkenntnis': '👁️',
	'Metallbearbeitung': '🔨',
	'Musizieren': '🎼',
	'Orientierung': '🧭',
	'Pflanzenkunde': '🌿',
	'Rechnen': '🧮',
	'Rechtskunde': '📚',
	'Reiten': '🐎',
	'Sagen & Legenden': '📖',
	'Schlösserknacken': '🔐',
	'Schwimmen': '🏊',
	'Selbstbeherrschung': '🧘',
	'Singen': '🎤',
	'Sinnesschärfe': '👀',
	'Sphärenkunde': '🌌',
	'Steinbearbeitung': '🪨',
	'Sternkunde': '✨',
	'Stoffbearbeitung': '🪡',
	'Tanzen': '💃',
	'Taschendiebstahl': '🫳',
	'Tierkunde': '🐾',
	'Überreden': '💬',
	'Verbergen': '🫥',
	'Verkleiden': '🎭',
	'Wildnisleben': '🏕️',
	'Willenskraft': '✊',
	'Zechen': '🍺',
});

const ZAUBER_QUICK_BUTTON_ICONS = Object.freeze({
	Ablativum: '🛡️',
	Affenarme: '🐒',
	Affenruf: '🐒',
	Adlerschwinge: '🦅',
	Abvenenum: '🧪',
	Adlerauge: '👁️',
	Aeolito: '🌪️',
	Alpgestalt: '😈',
	Altisonus: '📣',
	'Analys Arkanstruktur': '🔍',
	'Angst auslösen': '😨',
	Aquafaxius: '💧',
	Aquasphaero: '🫧',
	Arachnea: '🕸️',
	Archofaxius: '💥',
	Archosphaero: '☄️',
	Armatrutz: '🛡️',
	'Aromatis Illusionis': '🌸',
	Atemnot: '😮‍💨',
	'Attributo (Körperkraft)': '💪',
	'Attributo (Charisma)': '✨',
	'Attributo (Fingerfertigkeit)': '🤏',
	'Attributo (Gewandtheit)': '🤸',
	'Attributo (Intuition)': '🧠',
	'Attributo (Klugheit)': '📘',
	'Attributo (Konstitution)': '🫀',
	'Attributo (Mut)': '🦁',
	Aufwecken: '⏰',
	'Auge des Limbus': '🌀',
	'Aura der Erschöpfung': '🪫',
	'Auris Illusionis': '🎧',
	Avilea: '🕊️',
	Axxeleratus: '⚡',
	Balsam: '💚',
	'Balsam Salabunde': '💚',
	'Band und Fessel': '⛓️',
	Basaltleib: '🪨',
	Aureolus: '💫',
	Bannbaladin: '💞',
	'Blick aufs Wesen': '🧿',
	'Blick in die Gedanken': '🧠',
	Blindheit: '🙈',
	'Blitz dich find': '⚡',
	Blitzball: '🔆',
	'Böser Blick': '😈',
	'Brazoraghs Hieb': '🪓',
	Brandungsleib: '🌊',
	'Brennender Hass': '😡',
	Chamaelioni: '🦎',
	Claudibus: '🚪',
	Corpofrigo: '🥶',
	Corpofesso: '🥴',
	Debilitatio: '📉',
	Desintegratus: '💥',
	Disruptivo: '💣',
	Dornenwand: '🌵',
	Drachenleib: '🐉',
	Duplicatus: '🪞',
	Dunkelheit: '🌑',
	Dämonenbann: '⛔',
	Dämonenschild: '🔰',
	'Dämonisches Vergessen': '🫥',
	Ecliptifactus: '🌘',
	Eichenleib: '🌳',
	'Einflussbann': '🚫',
	Eisenrost: '⛓️',
	'Eigene Dummheit': '🙃',
	'Eigene Ängste': '😰',
	Elementarbann: '🚫',
	'Erinnerung verlasse dich': '🧠',
	Eispfeil: '🧊',
	Eiswand: '🧊',
	Elfenstimme: '🎶',
	Erzpfeil: '🪨',
	'Erschöpfungen lindern': '🛌',
	Eulenruf: '🦉',
	Exposami: '🔦',
	Favilludo: '✨',
	Falkenauge: '🦅',
	Federleib: '🪶',
	Feenstaub: '🧚',
	Fesselfeld: '🕸️',
	Fischflosse: '🐟',
	Firnlauf: '🛷',
	Fledermausruf: '🦇',
	Feuerpfeil: '🔥',
	'Flim Flam': '🕯️',
	Flammenwand: '🚧',
	Foramen: '🕳️',
	Fortifex: '🧱',
	Frostleib: '🥶',
	Frigifaxius: '❄️',
	Frigisphaero: '🧊',
	Fulminictus: '🌩️',
	Gefunden: '🧭',
	Gardianum: '🫧',
	Gedankenbilder: '🖼️',
	Geisteressenz: '👻',
	Gifthaut: '☣️',
	Glutlauf: '🔥',
	'Große Gier': '💰',
	'Große Verwirrung': '😵',
	Halluzination: '🌀',
	'Harmlose Gestalt': '🎭',
	Haselbusch: '🌿',
	Heilungsbann: '🚫',
	Hellsichtbann: '🙈',
	'Herzschlag ruhe': '🫀',
	'Herr über das Tierreich': '🐾',
	Heptagramma: '⭐',
	Hexagramma: '✡️',
	Hexengalle: '🧪',
	Hexenknoten: '🪢',
	Hexenkrallen: '🦅',
	Hexenholz: '🪵',
	Hexenspeichel: '🫗',
	'Hilfreiche Pfote': '🐾',
	'Hilfreiche Schwinge': '🪽',
	'Hilfreiche Tatze': '🐻',
	Himmelslauf: '☁️',
	Hornissenruf: '🐝',
	Horriphobus: '😱',
	Humofaxius: '🌿',
	Humosphaero: '🌱',
	Humuspfeil: '🌿',
	Höllenpein: '😈',
	Ignifaxius: '🔥',
	Ignisphaero: '☄️',
	Ignorantia: '🙈',
	Illusionsbann: '🚫',
	Imperavi: '👑',
	Impersona: '🎭',
	Incendio: '🔥',
	Invercano: '🪄',
	Invinculo: '⛓️',
	'Invocatio Minima': '🕯️',
	Karnifilo: '🦷',
	Katzenaugen: '🐈',
	Katzenruf: '🐈',
	'Krabbelnder Schrecken': '🪳',
	'Kraft aus Schmerzen': '🩸',
	'Kraft des Tieres': '🐾',
	'Krähenruf': '🐦',
	'Klarum Purum': '✨',
	Kulminatio: '⚡',
	Krötensprung: '🐸',
	Kusch: '🐕',
	'Last des Alters': '🕰️',
	'Levthans Feuer': '❤️‍🔥',
	'Luftpfeil': '💨',
	'Lunge des Leviatan': '🐋',
	'Mal der Erschöpfung': '🪫',
	'Mal der Schwäche': '📉',
	Manifesto: '✨',
	'Manus Illusionis': '🫴',
	'Manus Miracula': '🖐️',
	Memorans: '📚',
	Menetekel: '🪧',
	Motoricus: '🫳',
	Nebelform: '🌫️',
	Nebelwand: '🌁',
	Nuntiovolo: '🕊️',
	'Odem Arcanum': '👃',
	Objectofixo: '📌',
	Objectovoco: '🧲',
	'Oculus Astralis': '🔮',
	Paralysis: '🫸',
	Penetrizzel: '🧿',
	Plumbumbarum: '🪨',
	Respondami: '🗨️',
	Schlachtlied: '🎺',
	Silentium: '🤫',
	Somnigravis: '💤',
	Spinnenlauf: '🕷️',
	Transversalis: '🌀',
	Visibili: '👻',
	Wasseratem: '🌊',
	Wellenlauf: '🏄',
	'Woge der Versteinerung': '🪨',
	Wüstenlauf: '🏜️',
	'Zauberpferd herbeirufen': '🐎',
	'Zorn der Elemente': '🌩️',
	Wolfstatze: '🐺',
	'Zunge betäuben': '👅',
	Zitterfinger: '🫨',
	Zwingtanz: '💃',
	'Zweifel schüren': '🤨',
	'Ängste lindern': '🫶',
	Objektbann: '🚫',
	'Oculus Illusionis': '👁️',
	Objectobscuro: '🕶️',
	Pandaemonium: '😵',
	Oktagramma: '✴️',
	'Panik überkomme euch': '😱',
	Orcanofaxius: '🌪️',
	Orcanosphaero: '🌪️',
	Pentagramma: '⭐',
	'Pestilenz erspüren': '🤢',
	Pestodem: '☣️',
	Physiostabilis: '🩺',
	Projectimago: '🎥',
	Psychostabilis: '🧠',
	Radau: '🔊',
	Reflectimago: '🪞',
	Regeneratio: '💖',
	Reptilea: '🐍',
	Salander: '🦎',
	'Sanfter Fall': '🪂',
	Sanftmut: '🕊️',
	'Satuarias Herrlichkeit': '👸',
	Sapefacta: '🐗',
	'Schimmernder Schild': '🛡️',
	Schlangenruf: '🐍',
	'Schlechte Ausstrahlung': '😒',
	'Schleier der Unwissenheit': '🫥',
	'Schmerzen lindern': '🩹',
	Schuppenhaut: '🐉',
	'Schwarz und Rot': '🟥',
	'Schwarzer Schrecken': '👻',
	'Seelentier erkennen': '🐾',
	Seidenzunge: '👄',
	Sensattacco: '⚔️',
	Sensibar: '📡',
	Serpentialis: '🐍',
	Sinesigil: '✒️',
	Skelettarius: '🦴',
	Solidirid: '🧱',
	Sphärenbann: '🌌',
	Spinnenruf: '🕷️',
	Spurlos: '👣',
	Standfest: '🪵',
	Steinwand: '🪨',
	Stillstand: '⏸️',
	'Sturm der Verunsicherung': '🌪️',
	Sturmwand: '🌬️',
	'Sumus Elixiere': '🧪',
	Taubheit: '🙉',
	Telekinesebann: '🚫',
	Temporalbann: '⏳',
	'Tempus Stasis': '⌛',
	'Tiere besprechen': '🗣️',
	Tiergedanken: '🐾',
	Ungeschickt: '🤹',
	Unentflammbarkeit: '🧯',
	Verunsicherung: '😕',
	Verwandlungsbann: '🚫',
	Vipernblick: '🐍',
	Vogelzwitschern: '🐦',
	'Welle der Reinigung': '💦',
	'Welle des Schmerzes': '🌊',
	Wasserpfeil: '💧',
	Wellenwand: '🌊',
	Wipfellauf: '🌲',
});

const PROBE_SPECIFIC_EMOJI_MAPPINGS = Object.freeze({
	talente: TALENT_QUICK_BUTTON_ICONS,
	zauber: ZAUBER_QUICK_BUTTON_ICONS,
});

const PROBE_CATEGORY_EMOJIS = Object.freeze({
	zauber: '🪄',
	elfenlieder: '🧝',
	liturgien: '😇',
	rituale: '🔯',
	talente: '💪',
});

export const getQuickProbeEmoji = ({ category, name }) => {
	const categoryMapping = PROBE_SPECIFIC_EMOJI_MAPPINGS[category];
	if (name && categoryMapping?.[name]) {
		return categoryMapping[name];
	}

	return PROBE_CATEGORY_EMOJIS[category] ?? '💪';
};

export { TALENT_QUICK_BUTTON_ICONS, ZAUBER_QUICK_BUTTON_ICONS, PROBE_CATEGORY_EMOJIS };