const noOpEffect = {
	isApplyable: () => false,
	apply: ({ event }) => ({ ...event }),
};

const noOpEffects = [noOpEffect];
const noOpSonderfertigkeit = (name) => ({ name, pre: noOpEffects, post: noOpEffects });

const customSonderfertigkeiten = [
	{
		name: 'Lieblingszauber',
		pre: noOpEffects,
		post: [
			{
				isApplyable: (props) => {
					const {
						event,
						character: {
							sonderfertigkeiten: characterSonderfertigkeiten = [],
						} } = props;
					return characterSonderfertigkeiten.find(cs =>
						cs.name === 'Lieblingszauber'
                        && cs.referenz === event.talent.name);
				},
				apply: (props) => {
					const { event } = props;
					const oldFW = event.fw;
					if (event.bestanden === true && event.fw < 18) {
						event.fw = event.fw + 2;
						event.fw = Math.min(event.fw, 18);
						event.infos = event.infos ?? [];
						const info = {
							id: `Lieblingszauber (${event.fertigkeit?.name})`,
							text: `Lieblingszauber gewährte +2 FP: ${oldFW} → ${oldFW >= 17 ? '18 (max)' : event.fw} FP`,
						};
						event.infos.push(info);
					}

					return { ...event };
				},
			},
		],
	},
];

const sonderfertigkeiten = [
	noOpSonderfertigkeit('Abgeschwächte Liturgie'),
	noOpSonderfertigkeit('Aspektkenntnis'),
	noOpSonderfertigkeit('Blutpfand'),
	noOpSonderfertigkeit('Chimärenschreck'),
	noOpSonderfertigkeit('Daimonidenschreck'),
	noOpSonderfertigkeit('Entrückungsmeditation'),
	noOpSonderfertigkeit('Extrem starke Segnungen'),
	noOpSonderfertigkeit('Extrem starker Segnungsbruch'),
	noOpSonderfertigkeit('Fokussierung'),
	noOpSonderfertigkeit('Furcht nehmen'),
	noOpSonderfertigkeit('Gefestigter Zeremonieablauf'),
	noOpSonderfertigkeit('Geisterschreck'),
	noOpSonderfertigkeit('Geweihter Karmalleib'),
	noOpSonderfertigkeit('Golemschreck'),
	noOpSonderfertigkeit('Großer Festritus'),
	noOpSonderfertigkeit('Göttlicher Schutz'),
	noOpSonderfertigkeit('Hauptsegnung I-III'),
	noOpSonderfertigkeit('Heiliger Karmalleib'),
	noOpSonderfertigkeit('Hohe Weihe I-III'),
	noOpSonderfertigkeit('Improvisierte Liturgie (Gebet)'),
	noOpSonderfertigkeit('Improvisierte Liturgie (Gesten)'),
	noOpSonderfertigkeit('Karmale Meditation'),
	noOpSonderfertigkeit('Karmale Regeneration I-II'),
	noOpSonderfertigkeit('Klarer Blick'),
	noOpSonderfertigkeit('Kontrolle des Karmalkörpers'),
	noOpSonderfertigkeit('Lieblingsliturgie'),
	noOpSonderfertigkeit('Liturgie abbrechen'),
	noOpSonderfertigkeit('Liturgie vereinen I-II'),
	noOpSonderfertigkeit('Mauer des Geistes'),
	noOpSonderfertigkeit('Mirakelmacht'),
	noOpSonderfertigkeit('Mächtige Kontrolle des Karmalkörpers'),
	noOpSonderfertigkeit('Routinierte Liturgiewiederholung'),
	noOpSonderfertigkeit('Schild des Glaubens'),
	noOpSonderfertigkeit('Segnungsbruch'),
	noOpSonderfertigkeit('Stabile Regeneration'),
	noOpSonderfertigkeit('Starke Segnungen'),
	noOpSonderfertigkeit('Starker Segnungsbruch'),
	noOpSonderfertigkeit('Stärke des Glaubens'),
	noOpSonderfertigkeit('Traumweber I-III'),
	noOpSonderfertigkeit('Untotenschreck'),
	noOpSonderfertigkeit('Wahre Stärke des Glaubens'),
	noOpSonderfertigkeit('Wahrer Glaube'),
	noOpSonderfertigkeit('Zeremonialgegenstände herstellen'),
	noOpSonderfertigkeit('Zurück in die Niederhöllen'),
	noOpSonderfertigkeit('Zwei Segnungen gleichzeitig'),
	noOpSonderfertigkeit('Zweifachgeweihter Karmalleib'),
	noOpSonderfertigkeit('Altes Zwergenwissen'),
	noOpSonderfertigkeit('Aufbegehren'),
	noOpSonderfertigkeit('Aussaugen'),
	noOpSonderfertigkeit('Bannmeister'),
	noOpSonderfertigkeit('Einschüchternde Zurechtweisung'),
	noOpSonderfertigkeit('Erforscher des Rausches'),
	noOpSonderfertigkeit('Erzwungene Liturgie'),
	noOpSonderfertigkeit('Gebieter des (Aspekts)'),
	noOpSonderfertigkeit('Geistergefäß'),
	noOpSonderfertigkeit('Geistkontrolle'),
	noOpSonderfertigkeit('Gespür für Drachenwerk'),
	noOpSonderfertigkeit('Gesunder Geist, gesunder Körper'),
	noOpSonderfertigkeit('Geteilte Freude'),
	noOpSonderfertigkeit('Giftkenntnis'),
	noOpSonderfertigkeit('Guter Handel'),
	noOpSonderfertigkeit('Handwerksgespür'),
	noOpSonderfertigkeit('Harmonie der Seele'),
	noOpSonderfertigkeit('Heilritus'),
	noOpSonderfertigkeit('Hitzegewöhnung'),
	noOpSonderfertigkeit('Krankheitskenntnis'),
	noOpSonderfertigkeit('Kältegewöhnung'),
	noOpSonderfertigkeit('Körperkontrolle'),
	noOpSonderfertigkeit('Langanhaltender Segen'),
	noOpSonderfertigkeit('Missionierung'),
	noOpSonderfertigkeit('Omen'),
	noOpSonderfertigkeit('Schutz der Unsterblichen'),
	noOpSonderfertigkeit('Stille Andacht'),
	noOpSonderfertigkeit('Stille Meditation'),
	noOpSonderfertigkeit('Stilles Gebet'),
	noOpSonderfertigkeit('Tapferkeit der Unsterblichen'),
	noOpSonderfertigkeit('Verbesserte Fokussierung'),
	noOpSonderfertigkeit('Wohlklang der Seele'),
	noOpSonderfertigkeit('Überträger des Leids'),
	noOpSonderfertigkeit('Tradition (Angroschkirche)'),
	noOpSonderfertigkeit('Tradition (Aveskirche)'),
	noOpSonderfertigkeit('Tradition (Boronkirche)'),
	noOpSonderfertigkeit('Tradition (Efferdkirche)'),
	noOpSonderfertigkeit('Tradition (Ferkinaschamanen)'),
	noOpSonderfertigkeit('Tradition (Firunkirche)'),
	noOpSonderfertigkeit('Tradition (Fjarningerschamanen)'),
	noOpSonderfertigkeit('Tradition (Gjalskerschamanen)'),
	noOpSonderfertigkeit('Tradition (Hesindekirche)'),
	noOpSonderfertigkeit('Tradition (Ifirnkirche)'),
	noOpSonderfertigkeit('Tradition (Ingerimmkirche)'),
	noOpSonderfertigkeit('Tradition (Korkirche)'),
	noOpSonderfertigkeit('Tradition (Levthankult)'),
	noOpSonderfertigkeit('Tradition (Marbokult)'),
	noOpSonderfertigkeit('Tradition (Mohaschamanen)'),
	noOpSonderfertigkeit('Tradition (Namenloser Kult)'),
	noOpSonderfertigkeit('Tradition (Nanduskirche)'),
	noOpSonderfertigkeit('Tradition (Nivesenschamanen)'),
	noOpSonderfertigkeit('Tradition (Numinorukult)'),
	noOpSonderfertigkeit('Tradition (Perainekirche)'),
	noOpSonderfertigkeit('Tradition (Phexkirche)'),
	noOpSonderfertigkeit('Tradition (Praioskirche)'),
	noOpSonderfertigkeit('Tradition (Rahjakirche)'),
	noOpSonderfertigkeit('Tradition (Rondrakirche)'),
	noOpSonderfertigkeit('Tradition (Swafnirkirche)'),
	noOpSonderfertigkeit('Tradition (Traviakirche)'),
	noOpSonderfertigkeit('Tradition (Trollzackerschamanen)'),
	noOpSonderfertigkeit('Tradition (Tsakirche)'),
	noOpSonderfertigkeit('Anhänger des Güldenen'),
	noOpSonderfertigkeit('Anhänger des guten Kampfes'),
	noOpSonderfertigkeit('Anhänger des roten Gottes'),
	noOpSonderfertigkeit('Apricarier'),
	noOpSonderfertigkeit('Bilderstürmer'),
	noOpSonderfertigkeit('Braniborier'),
	noOpSonderfertigkeit('Deuter der Träume'),
	noOpSonderfertigkeit('Diebe des Nachthimmels'),
	noOpSonderfertigkeit('Dienerinnen der Nacht'),
	noOpSonderfertigkeit('Flusswächter'),
	noOpSonderfertigkeit('Freidenker'),
	noOpSonderfertigkeit('Friedensfreunde'),
	noOpSonderfertigkeit('Gehörnte'),
	noOpSonderfertigkeit('Geisterführer'),
	noOpSonderfertigkeit('Graugänse'),
	noOpSonderfertigkeit('Harmonisten'),
	noOpSonderfertigkeit('Hausgänse'),
	noOpSonderfertigkeit('Heiler der Gütigen'),
	noOpSonderfertigkeit('Heilerinnen des Leids'),
	noOpSonderfertigkeit('Helfer der Gütigen'),
	noOpSonderfertigkeit('Honoren'),
	noOpSonderfertigkeit('Händler des Listenreichen'),
	noOpSonderfertigkeit('Hüter der Esse'),
	noOpSonderfertigkeit('Hüter der Tradition'),
	noOpSonderfertigkeit('Hüter der Wacht'),
	noOpSonderfertigkeit('Hüter der Walwütigen'),
	noOpSonderfertigkeit('Hüterinnen der Schwänin'),
	noOpSonderfertigkeit('Jäger der Seeschlangen'),
	noOpSonderfertigkeit('Jägerinnen der weißen Maid'),
	noOpSonderfertigkeit('Jünger des Handwerks'),
	noOpSonderfertigkeit('Kamerad des guten Goldes'),
	noOpSonderfertigkeit('Kinder der Ratte'),
	noOpSonderfertigkeit('Kultisten des Ingra'),
	noOpSonderfertigkeit('Küstenwächter'),
	noOpSonderfertigkeit('Lehrer der Einsicht'),
	noOpSonderfertigkeit('Levthansfreunde'),
	noOpSonderfertigkeit('Medizinleute'),
	noOpSonderfertigkeit('Meereswächter'),
	noOpSonderfertigkeit('Naaghot-Shaar-Kultisten'),
	noOpSonderfertigkeit('Pastori'),
	noOpSonderfertigkeit('Priester des Weins'),
	noOpSonderfertigkeit('Prinzipisten'),
	noOpSonderfertigkeit('Propheten des Todes'),
	noOpSonderfertigkeit('Radscha-Anhänger'),
	noOpSonderfertigkeit('Salutaristen'),
	noOpSonderfertigkeit('Satori'),
	noOpSonderfertigkeit('Seher der Seele'),
	noOpSonderfertigkeit('Seher des verborgenen Pfades'),
	noOpSonderfertigkeit('Spitzel des Fuchses'),
	noOpSonderfertigkeit('Sucher der Erkenntnis'),
	noOpSonderfertigkeit('Säer der Gütigen'),
	noOpSonderfertigkeit('Tierpriester'),
	noOpSonderfertigkeit('Vigilanten'),
	noOpSonderfertigkeit('Waldläufer'),
	noOpSonderfertigkeit('Wanderer'),
	noOpSonderfertigkeit('Wiedergeborene'),
	noOpSonderfertigkeit('Wildgänse'),
	noOpSonderfertigkeit('Wildhüter'),
	noOpSonderfertigkeit('Zugvögel'),
	noOpSonderfertigkeit('Predigt der Gemeinschaft'),
	noOpSonderfertigkeit('Predigt der Zuversicht'),
	noOpSonderfertigkeit('Predigt des Gottvertrauens'),
	noOpSonderfertigkeit('Predigt des Wohlgefallens'),
	noOpSonderfertigkeit('Predigt wider Missgeschicke'),
	noOpSonderfertigkeit('Vision der Bestimmung'),
	noOpSonderfertigkeit('Vision der Entrückung'),
	noOpSonderfertigkeit('Vision der Gottheit'),
	noOpSonderfertigkeit('Vision des Schicksals'),
	noOpSonderfertigkeit('Vision des Wahren Glaubens'),
	noOpSonderfertigkeit('Angroschanhänger (Angrosch)'),
	noOpSonderfertigkeit('Avesstab (Aves)'),
	noOpSonderfertigkeit('Buch der Schlange (Hesinde)'),
	noOpSonderfertigkeit('Efferdbart (Efferd)'),
	noOpSonderfertigkeit('Einhornstirnband (Nandus)'),
	noOpSonderfertigkeit('Firunsmesser (Firun)'),
	noOpSonderfertigkeit('Grüne Handschuhe (Peraine)'),
	noOpSonderfertigkeit('Gänsebeutel (Travia)'),
	noOpSonderfertigkeit('Ifirnsmantel (Ifirn)'),
	noOpSonderfertigkeit('Ingerimmshammer (Ingerimm)'),
	noOpSonderfertigkeit('Knochenkeule (Ferkinaschamanen)'),
	noOpSonderfertigkeit('Knochenkeule (Fjarninger)'),
	noOpSonderfertigkeit('Knochenkeule (Gjalskerschamanen)'),
	noOpSonderfertigkeit('Knochenkeule (Mohaschamanen)'),
	noOpSonderfertigkeit('Knochenkeule (Nievesenschamanen)'),
	noOpSonderfertigkeit('Knochenkeule (Trollzackerschamanen)'),
	noOpSonderfertigkeit('Knochenkeule der Schamanen (Tairach)'),
	noOpSonderfertigkeit('Korspieß (Kor)'),
	noOpSonderfertigkeit('Marbodolch (Marbo)'),
	noOpSonderfertigkeit('Mondamulett (Phex)'),
	noOpSonderfertigkeit('Muschelhorn (Numinoru)'),
	noOpSonderfertigkeit('Opferdolch des Namenlosen (Namenloser)'),
	noOpSonderfertigkeit('Prisma (Tsa)'),
	noOpSonderfertigkeit('Rabenschnabel (Boron)'),
	noOpSonderfertigkeit('Rondrakamm (Rondra)'),
	noOpSonderfertigkeit('Roter Schleier (Rahja)'),
	noOpSonderfertigkeit('Sonnenzepter (Praios)'),
	noOpSonderfertigkeit('Walschild (Swafnir)'),
	noOpSonderfertigkeit('Widderkeule (Levthankult)'),
	noOpSonderfertigkeit('Abgeschwächter Zauber'),
	noOpSonderfertigkeit('Abnehmbare Magierkugel'),
	noOpSonderfertigkeit('Adaption (Zauber)'),
	noOpSonderfertigkeit('Alchimieverstärkung'),
	noOpSonderfertigkeit('Astrale Meditation'),
	noOpSonderfertigkeit('Aura verbergen'),
	noOpSonderfertigkeit('Aurapanzer'),
	noOpSonderfertigkeit('Bindung (Dämonen)'),
	noOpSonderfertigkeit('Blutmagie (Selbstopfer)'),
	noOpSonderfertigkeit('Chimärenmeister'),
	noOpSonderfertigkeit('Daimonidenkonstrukteur'),
	noOpSonderfertigkeit('Druidenrache'),
	noOpSonderfertigkeit('Eisen- und Stahlverzauberung'),
	noOpSonderfertigkeit('Entschwörung (Dämonen)'),
	noOpSonderfertigkeit('Entschwörung (Elementare)'),
	noOpSonderfertigkeit('Entschwörung (Geister)'),
	noOpSonderfertigkeit('Exorzist I-III'),
	noOpSonderfertigkeit('Extrem starke Zaubertricks'),
	noOpSonderfertigkeit('Exzellenter Entschwörer I-V'),
	noOpSonderfertigkeit('Fernzaubern'),
	noOpSonderfertigkeit('Flugsalbe'),
	noOpSonderfertigkeit('Gedankenschutz'),
	noOpSonderfertigkeit('Gefährliche Träume I-III'),
	noOpSonderfertigkeit('Gegenstände verfluchen'),
	noOpSonderfertigkeit('Gemeinsamer Fluch'),
	noOpSonderfertigkeit('Golembauer'),
	noOpSonderfertigkeit('Große Meditation I-III'),
	noOpSonderfertigkeit('Große Trankverdünnung'),
	noOpSonderfertigkeit('Hexentanz'),
	noOpSonderfertigkeit('Homunculusbindung'),
	noOpSonderfertigkeit('Imitationszauberei I-V'),
	noOpSonderfertigkeit('Improvisationszauberei (Formel)'),
	noOpSonderfertigkeit('Improvisationszauberei (Gesten)'),
	noOpSonderfertigkeit('Improvisiertes Ritual'),
	noOpSonderfertigkeit('Kleine Kraftkontrolle'),
	noOpSonderfertigkeit('Kleine Trankverdünnung'),
	noOpSonderfertigkeit('Kleines Salasandra'),
	noOpSonderfertigkeit('Koboldruf'),
	noOpSonderfertigkeit('Koboldvision'),
	noOpSonderfertigkeit('Konzentrationsstärke'),
	noOpSonderfertigkeit('Kraftknotenmagie'),
	noOpSonderfertigkeit('Kraftknotennutzung'),
	noOpSonderfertigkeit('Kraftkontrolle'),
	noOpSonderfertigkeit('Kraftlinienmagie'),
	noOpSonderfertigkeit('Kraftliniennutzung'),
	...customSonderfertigkeiten,
	noOpSonderfertigkeit('Lockeres Zaubern'),
	noOpSonderfertigkeit('Machtvolle Entschwörung (Dämonen)'),
	noOpSonderfertigkeit('Machtvolle Entschwörung (Elementare)'),
	noOpSonderfertigkeit('Machtvolle Entschwörung (Geister)'),
	noOpSonderfertigkeit('Machtvoller Astralleib'),
	noOpSonderfertigkeit('Magische Regeneration I-II'),
	noOpSonderfertigkeit('Magischer Gedankenschutz'),
	noOpSonderfertigkeit('Materielle Verbindung'),
	noOpSonderfertigkeit('Matrixkontrolle'),
	noOpSonderfertigkeit('Meisterliche Regeneration'),
	noOpSonderfertigkeit('Meistertrick I-III'),
	noOpSonderfertigkeit('Merkmalskenntnis'),
	noOpSonderfertigkeit('Nekromant'),
	noOpSonderfertigkeit('Parallelzauberei'),
	noOpSonderfertigkeit('Permanenter Fluch'),
	noOpSonderfertigkeit('Routinierte Zauberwiederholung'),
	noOpSonderfertigkeit('Rudelbeschwörung I/II//III'),
	noOpSonderfertigkeit('Sofortiger Fluch'),
	noOpSonderfertigkeit('Starke Zaubertricks'),
	noOpSonderfertigkeit('Traumzauberei I-III'),
	noOpSonderfertigkeit('Verbotene Pforten'),
	noOpSonderfertigkeit('Verschmelzung von Kulturschaffende'),
	noOpSonderfertigkeit('Verschmelzung von übernatürlichen Wesen'),
	noOpSonderfertigkeit('Vertrautenbindung'),
	noOpSonderfertigkeit('Vielfache Ladung'),
	noOpSonderfertigkeit('Wahrer Name (spezieller Dämon)'),
	noOpSonderfertigkeit('Zauber abbrechen'),
	noOpSonderfertigkeit('Zauber bereithalten'),
	noOpSonderfertigkeit('Zauber bündeln I-II'),
	noOpSonderfertigkeit('Zauber unterbrechen'),
	noOpSonderfertigkeit('Zauberkraft des Hains'),
	noOpSonderfertigkeit('Zauberstil-Kombination'),
	noOpSonderfertigkeit('Zauberzeichen'),
	noOpSonderfertigkeit('Zirkelmeister (Dämonen)'),
	noOpSonderfertigkeit('Alchimieanalytiker'),
	noOpSonderfertigkeit('Anatomische Magie'),
	noOpSonderfertigkeit('Artefaktanalytiker'),
	noOpSonderfertigkeit('Astralraub'),
	noOpSonderfertigkeit('Aufladung'),
	noOpSonderfertigkeit('Austreibung'),
	noOpSonderfertigkeit('Begnadeter Objektzauberer'),
	noOpSonderfertigkeit('Bewanderter Heilzauberer'),
	noOpSonderfertigkeit('Bewegungszauberei'),
	noOpSonderfertigkeit('Brillanter Telekinetiker'),
	noOpSonderfertigkeit('Destruktor'),
	noOpSonderfertigkeit('Dämonenmeisterin'),
	noOpSonderfertigkeit('Einlullende Zaubermusik'),
	noOpSonderfertigkeit('Eiserne Konzentrationsstärke'),
	noOpSonderfertigkeit('Elementarmeisterin'),
	noOpSonderfertigkeit('Elfenfreund'),
	noOpSonderfertigkeit('Erdkraft'),
	noOpSonderfertigkeit('Erfahrener Antimagier'),
	noOpSonderfertigkeit('Erschaffer'),
	noOpSonderfertigkeit('Erweiterter Gedankenschutz'),
	noOpSonderfertigkeit('Fluchmeisterin ( auch: Langer Fluch)'),
	noOpSonderfertigkeit('Freundliche Artefaktseele'),
	noOpSonderfertigkeit('Gegnerische Zauberpraxis (Element)'),
	noOpSonderfertigkeit('Geisterfreundin'),
	noOpSonderfertigkeit('Geistermedium'),
	noOpSonderfertigkeit('Geistzauberer'),
	noOpSonderfertigkeit('Giftmeisterin'),
	noOpSonderfertigkeit('Golemformer'),
	noOpSonderfertigkeit('Harmoniezauberei'),
	noOpSonderfertigkeit('Hervorragender Illusionist'),
	noOpSonderfertigkeit('Illusionäre Undurchschaubarkeit'),
	noOpSonderfertigkeit('Kesselmeisterin'),
	noOpSonderfertigkeit('Kriegszauberer'),
	noOpSonderfertigkeit('Kundiger Sphärologe'),
	noOpSonderfertigkeit('Langanhaltende Illusion'),
	noOpSonderfertigkeit('Langwirkende Artefakte'),
	noOpSonderfertigkeit('Liebeszauberei'),
	noOpSonderfertigkeit('Macht des Hasses'),
	noOpSonderfertigkeit('Machtvolle Verbotene Pforten'),
	noOpSonderfertigkeit('Machtvolle materielle Verbindung'),
	noOpSonderfertigkeit('Magische Kräuterheilkunde'),
	noOpSonderfertigkeit('Magischer Schutzschild'),
	noOpSonderfertigkeit('Matrixzauberei'),
	noOpSonderfertigkeit('Mehr Glück als Verstand'),
	noOpSonderfertigkeit('Meisterliches Auraverbergen'),
	noOpSonderfertigkeit('Mitverwandlung'),
	noOpSonderfertigkeit('Musikzauberei'),
	noOpSonderfertigkeit('Psychometrie'),
	noOpSonderfertigkeit('Qabalya-Magie'),
	noOpSonderfertigkeit('Selbstkontrolle'),
	noOpSonderfertigkeit('Selbstverzauberer'),
	noOpSonderfertigkeit('Tierflüsterer'),
	noOpSonderfertigkeit('Umfassende Telekinese'),
	noOpSonderfertigkeit('Unaufhaltsamkeit'),
	noOpSonderfertigkeit('Untotenmeister'),
	noOpSonderfertigkeit('Unverstellter Blick'),
	noOpSonderfertigkeit('Unübertroffener Verwandler'),
	noOpSonderfertigkeit('Urtulamidische Heilmagie'),
	noOpSonderfertigkeit('Verständigungszauberer'),
	noOpSonderfertigkeit('Vollendeter Elementarist'),
	noOpSonderfertigkeit('Vollkommener Beherrscher'),
	noOpSonderfertigkeit('Vortrefflicher Hellseher'),
	noOpSonderfertigkeit('Weissagung'),
	noOpSonderfertigkeit('Wissensaustausch'),
	noOpSonderfertigkeit('Zauberkämpfer'),
	noOpSonderfertigkeit('Zauberobjekte'),
	noOpSonderfertigkeit('Überragender Dämonologe'),
	noOpSonderfertigkeit('Übertragung der Astralkräfte'),
	noOpSonderfertigkeit('Übertragung der Lebenskraft'),
	noOpSonderfertigkeit('Alraunenbeere'),
	noOpSonderfertigkeit('Alraunenschrei'),
	noOpSonderfertigkeit('Elixierspeicher'),
	noOpSonderfertigkeit('Giftabsorption'),
	noOpSonderfertigkeit('Heilendes Raunen'),
	noOpSonderfertigkeit('Ingredienz erspüren'),
	noOpSonderfertigkeit('Ausdauerndes Werwesen'),
	noOpSonderfertigkeit('Intelligentes Werwesen'),
	noOpSonderfertigkeit('Selbstbestimmter Verwandlungszeitpunkt I-III'),
	noOpSonderfertigkeit('Tradition (Animisten)'),
	noOpSonderfertigkeit('Tradition (Brobim-Geoden)'),
	noOpSonderfertigkeit('Tradition (Druiden)'),
	noOpSonderfertigkeit('Tradition (Dämonen)'),
	noOpSonderfertigkeit('Tradition (Einhorn)'),
	noOpSonderfertigkeit('Tradition (Elfen)'),
	noOpSonderfertigkeit('Tradition (Feen)'),
	noOpSonderfertigkeit('Tradition (Geoden)'),
	noOpSonderfertigkeit('Tradition (Gildenmagier)'),
	noOpSonderfertigkeit('Tradition (Goblinzauberinnen)'),
	noOpSonderfertigkeit('Tradition (Hexen)'),
	noOpSonderfertigkeit('Tradition (Meistertalentierte)'),
	noOpSonderfertigkeit('Tradition (Nachtalben)'),
	noOpSonderfertigkeit('Tradition (Necker)'),
	noOpSonderfertigkeit('Tradition (Qabalyamagier)'),
	noOpSonderfertigkeit('Tradition (Scharlatane)'),
	noOpSonderfertigkeit('Tradition (Schelme)'),
	noOpSonderfertigkeit('Tradition (Sphinx)'),
	noOpSonderfertigkeit('Tradition (Tsatuara-Anhängerinnen)'),
	noOpSonderfertigkeit('Tradition (Zauberalchimisten)'),
	noOpSonderfertigkeit('Tradition (Zauberbarden)'),
	noOpSonderfertigkeit('Tradition (Zaubertänzer)'),
	noOpSonderfertigkeit('Tradition (Zibilja)'),
	noOpSonderfertigkeit('Tradition (intuitiver Zauberer)'),
	noOpSonderfertigkeit('Blick des Nachtmahrs'),
	noOpSonderfertigkeit('Blutdurst der Fledermaus'),
	noOpSonderfertigkeit('Kuss der Todesfee'),
	noOpSonderfertigkeit('Macht des Sukkubus'),
	noOpSonderfertigkeit('Ahnenzeichen'),
	noOpSonderfertigkeit('Abrichter'),
	noOpSonderfertigkeit('Abrollen'),
	noOpSonderfertigkeit('Abschleppspezialist/in'),
	noOpSonderfertigkeit('Ackerbau'),
	noOpSonderfertigkeit('Alchimistische Äquivalenzlehre'),
	noOpSonderfertigkeit('Analytiker'),
	noOpSonderfertigkeit('Anatomie (Spezies)'),
	noOpSonderfertigkeit('Anführer'),
	noOpSonderfertigkeit('Anpeitscher'),
	noOpSonderfertigkeit('Architekt'),
	noOpSonderfertigkeit('Archivar'),
	noOpSonderfertigkeit('Athlet'),
	noOpSonderfertigkeit('Bastler'),
	noOpSonderfertigkeit('Bauchreden'),
	noOpSonderfertigkeit('Baumeisterin'),
	noOpSonderfertigkeit('Beeindruckende Vorstellung'),
	noOpSonderfertigkeit('Bergbau'),
	noOpSonderfertigkeit('Bernstein erhitzen'),
	noOpSonderfertigkeit('Berufsgeheimnisse'),
	noOpSonderfertigkeit('Bierbrauerei'),
	noOpSonderfertigkeit('Bildhauerei'),
	noOpSonderfertigkeit('Bine Maschores'),
	noOpSonderfertigkeit('Bootsbauer'),
	noOpSonderfertigkeit('Buchdrucker'),
	noOpSonderfertigkeit('Deichbauer'),
	noOpSonderfertigkeit('Diener'),
	noOpSonderfertigkeit('Dokumentfälscher'),
	noOpSonderfertigkeit('Drohgebärden'),
	noOpSonderfertigkeit('Edelsteinschleifen'),
	noOpSonderfertigkeit('Eiserner Wille I-II'),
	noOpSonderfertigkeit('Elegante Frisur'),
	noOpSonderfertigkeit('Entfernungen schätzen'),
	noOpSonderfertigkeit('Entfesselungskünstler'),
	noOpSonderfertigkeit('Erholsames Bad'),
	noOpSonderfertigkeit('Ermutigender Gesang'),
	noOpSonderfertigkeit('Fallen entschärfen'),
	noOpSonderfertigkeit('Fallen wieder scharfmachen'),
	noOpSonderfertigkeit('Fallenbaumeisterin'),
	noOpSonderfertigkeit('Fallentarnung'),
	noOpSonderfertigkeit('Falschspielen'),
	noOpSonderfertigkeit('Faszinierender Gesang'),
	noOpSonderfertigkeit('Fertigkeitsspezialisierung (Talente)'),
	noOpSonderfertigkeit('Feuerschlucker'),
	noOpSonderfertigkeit('Fischer'),
	noOpSonderfertigkeit('Flusslotse (Region)'),
	noOpSonderfertigkeit('Freiklettern'),
	noOpSonderfertigkeit('Fächersprache'),
	noOpSonderfertigkeit('Füchsisch'),
	noOpSonderfertigkeit('Galanterie'),
	noOpSonderfertigkeit('Geländekunde'),
	noOpSonderfertigkeit('Gerüchtekoch I-III'),
	noOpSonderfertigkeit('Gespür für Himmelsrichtungen'),
	noOpSonderfertigkeit('Gestählter Wille'),
	noOpSonderfertigkeit('Gift melken (Land- und Lufttiere)'),
	noOpSonderfertigkeit('Gift melken (Wassertiere)'),
	noOpSonderfertigkeit('Giftverstärkung (Giftart)'),
	noOpSonderfertigkeit('Gildenrecht'),
	noOpSonderfertigkeit('Glasbläserei'),
	noOpSonderfertigkeit('Guter Gardist, böser Gardist'),
	noOpSonderfertigkeit('Hauswirtschaft'),
	noOpSonderfertigkeit('Hehlerei'),
	noOpSonderfertigkeit('Heilungsspezialgebiet (Anwendungsgebiet)'),
	noOpSonderfertigkeit('Heraldik'),
	noOpSonderfertigkeit('Heraldikspezialist'),
	noOpSonderfertigkeit('Hinterhaltsspezialist'),
	noOpSonderfertigkeit('Hofzeremoniell'),
	noOpSonderfertigkeit('Holzkenntnis'),
	noOpSonderfertigkeit('Iglubau'),
	noOpSonderfertigkeit('Ingenieurin'),
	noOpSonderfertigkeit('Instrumente bauen'),
	noOpSonderfertigkeit('Jäger'),
	noOpSonderfertigkeit('Kalligraphie'),
	noOpSonderfertigkeit('Kampftrinker I-IV'),
	noOpSonderfertigkeit('Kapellmeister'),
	noOpSonderfertigkeit('Kartographie'),
	noOpSonderfertigkeit('Kohlezeichnungen'),
	noOpSonderfertigkeit('Konditor'),
	noOpSonderfertigkeit('Kristallzucht'),
	noOpSonderfertigkeit('Kryptographie'),
	noOpSonderfertigkeit('Kräutermischung'),
	noOpSonderfertigkeit('Kunstflug'),
	noOpSonderfertigkeit('Kunstreiten'),
	noOpSonderfertigkeit('Kupferstich'),
	noOpSonderfertigkeit('Kurzschrift'),
	noOpSonderfertigkeit('Kutschenbauer'),
	noOpSonderfertigkeit('Leg-ga-leg'),
	noOpSonderfertigkeit('Lehrer I-III'),
	noOpSonderfertigkeit('Leibdiener'),
	noOpSonderfertigkeit('Liebling der Massen'),
	noOpSonderfertigkeit('Lippenlesen'),
	noOpSonderfertigkeit('Masseur/in'),
	noOpSonderfertigkeit('Meister der Improvisation'),
	noOpSonderfertigkeit('Menschenstimmen imitieren'),
	noOpSonderfertigkeit('Möbel herstellen'),
	noOpSonderfertigkeit('Namensschmeichler'),
	noOpSonderfertigkeit('Navigation'),
	noOpSonderfertigkeit('Nerven aus Stahl'),
	noOpSonderfertigkeit('Opernsänger'),
	noOpSonderfertigkeit('Orientierung unter Tage'),
	noOpSonderfertigkeit('Ortskenntnis'),
	noOpSonderfertigkeit('Pflanzen erhalten'),
	noOpSonderfertigkeit('Porzellanarbeiten'),
	noOpSonderfertigkeit('Provozieren'),
	noOpSonderfertigkeit('Prunkkleidung herstellen'),
	noOpSonderfertigkeit('Pyromantiker'),
	noOpSonderfertigkeit('Rahjasutra-Kenntnisse'),
	noOpSonderfertigkeit('Rosstäuscher'),
	noOpSonderfertigkeit('Rüstungsbau'),
	noOpSonderfertigkeit('Sammler'),
	noOpSonderfertigkeit('Schiffsbauer'),
	noOpSonderfertigkeit('Schleiertanz'),
	noOpSonderfertigkeit('Schmerzen unterdrücken'),
	noOpSonderfertigkeit('Schmuck herstellen'),
	noOpSonderfertigkeit('Schnapsbrennerei'),
	noOpSonderfertigkeit('Schnellschreiber'),
	noOpSonderfertigkeit('Schrift'),
	noOpSonderfertigkeit('Schriftstellerei'),
	noOpSonderfertigkeit('Seelotse (Region)'),
	noOpSonderfertigkeit('Seile herstellen'),
	noOpSonderfertigkeit('Selbstbewusstes Auftreten'),
	noOpSonderfertigkeit('Sinnlicher Tanz'),
	noOpSonderfertigkeit('Skifahren'),
	noOpSonderfertigkeit('Smutje'),
	noOpSonderfertigkeit('Sprache I-III'),
	noOpSonderfertigkeit('Sprache der Blumen'),
	noOpSonderfertigkeit('Staatskunst'),
	noOpSonderfertigkeit('Stechender Blick'),
	noOpSonderfertigkeit('Stellmacherei'),
	noOpSonderfertigkeit('Tierheilerin (Tierart)'),
	noOpSonderfertigkeit('Tierstimmen imitieren'),
	noOpSonderfertigkeit('Tierzüchter (Tierart)'),
	noOpSonderfertigkeit('Turnierkenntnis'),
	noOpSonderfertigkeit('Tätowierer'),
	noOpSonderfertigkeit('Töpferei'),
	noOpSonderfertigkeit('Unterminieren'),
	noOpSonderfertigkeit('Unterschlupf finden'),
	noOpSonderfertigkeit('Verführungskunst'),
	noOpSonderfertigkeit('Verstecke finden'),
	noOpSonderfertigkeit('Vieharzt (Tierart)'),
	noOpSonderfertigkeit('Viehzucht'),
	noOpSonderfertigkeit('Waffenbau'),
	noOpSonderfertigkeit('Wandmalerei'),
	noOpSonderfertigkeit('Wegabkürzungen kennen'),
	noOpSonderfertigkeit('Wegkenntnis'),
	noOpSonderfertigkeit('Werte schätzen'),
	noOpSonderfertigkeit('Wettervorhersage'),
	noOpSonderfertigkeit('Winzerei'),
	noOpSonderfertigkeit('Zahlenmystik'),
	noOpSonderfertigkeit('Ätzes geben'),
	noOpSonderfertigkeit('Ölmalerei'),
	noOpSonderfertigkeit('Befehl Flugangriff'),
	noOpSonderfertigkeit('Befehl Klammerangriff'),
	noOpSonderfertigkeit('Befehl Mächtiger Schlag'),
	noOpSonderfertigkeit('Befehl Sichelangriff'),
	noOpSonderfertigkeit('Befehl Trampeln'),
	noOpSonderfertigkeit('Befehl Überrennen'),
	noOpSonderfertigkeit('Angetäuschter Angriff'),
	noOpSonderfertigkeit('Angriff nach Hinten'),
	noOpSonderfertigkeit('Antäuschen'),
	noOpSonderfertigkeit('Aufliegende Klinge'),
	noOpSonderfertigkeit('Aufspießen'),
	noOpSonderfertigkeit('Berserkerangriff'),
	noOpSonderfertigkeit('Betäubendes Geschoss'),
	noOpSonderfertigkeit('Binden'),
	noOpSonderfertigkeit('Blattschuss'),
	noOpSonderfertigkeit('Blitzreflexe'),
	noOpSonderfertigkeit('Breschenangriff'),
	noOpSonderfertigkeit('Defensives Verhalten'),
	noOpSonderfertigkeit('Drachentod'),
	noOpSonderfertigkeit('Drehschlag'),
	noOpSonderfertigkeit('Drehwurf'),
	noOpSonderfertigkeit('Durchbohrung'),
	noOpSonderfertigkeit('Eisenfaust'),
	noOpSonderfertigkeit('Erweiterte Drachenkampf-Taktik'),
	noOpSonderfertigkeit('Extremschuss'),
	noOpSonderfertigkeit('Fahrender Schütze'),
	noOpSonderfertigkeit('Fixierungsschuss'),
	noOpSonderfertigkeit('Formationsattacke'),
	noOpSonderfertigkeit('Formationsparade'),
	noOpSonderfertigkeit('Frontalangriff'),
	noOpSonderfertigkeit('Fußfeger'),
	noOpSonderfertigkeit('Geschickter Wurf'),
	noOpSonderfertigkeit('Haltegriff brechen'),
	noOpSonderfertigkeit('Handkantenschlag'),
	noOpSonderfertigkeit('Hohe Klinge'),
	noOpSonderfertigkeit('Kopfstoß'),
	noOpSonderfertigkeit('Machtvoller Kernschuss'),
	noOpSonderfertigkeit('Machtvoller Sturmangriff'),
	noOpSonderfertigkeit('Machtvoller Wirbelangriff'),
	noOpSonderfertigkeit('Meister elfischer Waffen'),
	noOpSonderfertigkeit('Meister zwergischer Waffen'),
	noOpSonderfertigkeit('Meisterlicher Turnierreiter'),
	noOpSonderfertigkeit('Meisterlicher Wurf'),
	noOpSonderfertigkeit('Meisterliches Umrennen'),
	noOpSonderfertigkeit('Miese Tricks'),
	noOpSonderfertigkeit('Mächtiger Lanzenangriff'),
	noOpSonderfertigkeit('Mächtiger Rundumschlag'),
	noOpSonderfertigkeit('Nachladespezialist'),
	noOpSonderfertigkeit('Nervös machen'),
	noOpSonderfertigkeit('Offensives Verhalten'),
	noOpSonderfertigkeit('Reizen'),
	noOpSonderfertigkeit('Riskanter Schuss'),
	noOpSonderfertigkeit('Rückendeckung'),
	noOpSonderfertigkeit('Schilddeckung'),
	noOpSonderfertigkeit('Schildstoß'),
	noOpSonderfertigkeit('Schmerzwut'),
	noOpSonderfertigkeit('Schwinger'),
	noOpSonderfertigkeit('Sprung vom Reittier'),
	noOpSonderfertigkeit('Sprungangriff'),
	noOpSonderfertigkeit('Sprungtritt'),
	noOpSonderfertigkeit('Sprungwurf'),
	noOpSonderfertigkeit('Taktik durchbrechen'),
	noOpSonderfertigkeit('Taktische Befehle'),
	noOpSonderfertigkeit('Tiefe Wunde'),
	noOpSonderfertigkeit('Tiefschlag'),
	noOpSonderfertigkeit('Tod von Links'),
	noOpSonderfertigkeit('Verbesserte Aufmerksamkeit'),
	noOpSonderfertigkeit('Verbesserter Betäubungsschlag'),
	noOpSonderfertigkeit('Verbesserter Doppelangriff'),
	noOpSonderfertigkeit('Verbesserter Schwitzkasten'),
	noOpSonderfertigkeit('Verkürzte Waffenführung'),
	noOpSonderfertigkeit('Versteckte Klinge'),
	noOpSonderfertigkeit('Vorbeiziehen'),
	noOpSonderfertigkeit('Waffenwurf'),
	noOpSonderfertigkeit('Weiter Schwung'),
	noOpSonderfertigkeit('Windmühle'),
	noOpSonderfertigkeit('Wuchtiger Wurf'),
	noOpSonderfertigkeit('Würgegriff'),
	noOpSonderfertigkeit('Zertrümmern'),
	noOpSonderfertigkeit('Zweifacher Angriff'),
	noOpSonderfertigkeit('Allgemeinwissen'),
	noOpSonderfertigkeit('Bedrohliche Aura'),
	noOpSonderfertigkeit('Einnahmequelle'),
	noOpSonderfertigkeit('Entspannendes Liebesspiel'),
	noOpSonderfertigkeit('Erfolgreicher Jäger'),
	noOpSonderfertigkeit('Ermutigende Darstellung'),
	noOpSonderfertigkeit('Fachwissen'),
	noOpSonderfertigkeit('Faszinierende Darstellung'),
	noOpSonderfertigkeit('Fährtenleser'),
	noOpSonderfertigkeit('Gerüchte aufschnappen'),
	noOpSonderfertigkeit('Gesteinskunde'),
	noOpSonderfertigkeit('Grandioser Leibdiener'),
	noOpSonderfertigkeit('Großes Heilbad'),
	noOpSonderfertigkeit('Gute Verarbeitung'),
	noOpSonderfertigkeit('Handwerkskunst'),
	noOpSonderfertigkeit('Herrschaftsanspruch'),
	noOpSonderfertigkeit('Kind der Natur'),
	noOpSonderfertigkeit('Kopist'),
	noOpSonderfertigkeit('Kraftanstrengung'),
	noOpSonderfertigkeit('Kunstbegabt'),
	noOpSonderfertigkeit('Körperliches Geschick'),
	noOpSonderfertigkeit('Machtvoller Heiler'),
	noOpSonderfertigkeit('Meister der Orientierung'),
	noOpSonderfertigkeit('Meisterin der Tarnung'),
	noOpSonderfertigkeit('Meisterliche Kräutermischung'),
	noOpSonderfertigkeit('Phantastische Tätowierung'),
	noOpSonderfertigkeit('Rechnungswesen'),
	noOpSonderfertigkeit('Routinierte Wundversorgung'),
	noOpSonderfertigkeit('Seemannsgarn'),
	noOpSonderfertigkeit('Soziale Kompetenz'),
	noOpSonderfertigkeit('Tierverbundenheit'),
	noOpSonderfertigkeit('Täuschung der Zuschauer'),
	noOpSonderfertigkeit('Unauffälliger Griff'),
	noOpSonderfertigkeit('Universalgenie'),
	noOpSonderfertigkeit('Verhandlungsgeschick'),
	noOpSonderfertigkeit('Vertrauenswürdig'),
	noOpSonderfertigkeit('Armbrust überdrehen'),
	noOpSonderfertigkeit('Auf Distanz halten I-II'),
	noOpSonderfertigkeit('Auflaufen'),
	noOpSonderfertigkeit('Aufmerksamkeit'),
	noOpSonderfertigkeit('Ausfall I-II'),
	noOpSonderfertigkeit('Ballistischer Schuss'),
	noOpSonderfertigkeit('Beidhändiger Kampf I-II'),
	noOpSonderfertigkeit('Belastungsgewöhnung I-II'),
	noOpSonderfertigkeit('Berittene Lanzenformation'),
	noOpSonderfertigkeit('Berittener Flugkampf'),
	noOpSonderfertigkeit('Berittener Kampf'),
	noOpSonderfertigkeit('Berittener Schütze'),
	noOpSonderfertigkeit('Beschützer'),
	noOpSonderfertigkeit('Betäubungsschlag'),
	noOpSonderfertigkeit('Blindkampf I-II'),
	noOpSonderfertigkeit('Blutgrätsche'),
	noOpSonderfertigkeit('Doppelangriff'),
	noOpSonderfertigkeit('Drachenkampf-Taktik'),
	noOpSonderfertigkeit('Durchgezogener Tritt I-III'),
	noOpSonderfertigkeit('Einhändiger Kampf'),
	noOpSonderfertigkeit('Eisenhagel I-II'),
	noOpSonderfertigkeit('Ellbogenangriff I-III'),
	noOpSonderfertigkeit('Entwaffnen'),
	noOpSonderfertigkeit('Feindgespür'),
	noOpSonderfertigkeit('Festnageln'),
	noOpSonderfertigkeit('Finte I-III'),
	noOpSonderfertigkeit('Formation'),
	noOpSonderfertigkeit('Gefechtsformation'),
	noOpSonderfertigkeit('Gegenhalten'),
	noOpSonderfertigkeit('Geschossabwehr I-III'),
	noOpSonderfertigkeit('Geschütze bedienen'),
	noOpSonderfertigkeit('Gezielter Angriff'),
	noOpSonderfertigkeit('Gezielter Schuss'),
	noOpSonderfertigkeit('Grätsche'),
	noOpSonderfertigkeit('Haltegriff'),
	noOpSonderfertigkeit('Hammerschlag'),
	noOpSonderfertigkeit('Herunterstoßen'),
	noOpSonderfertigkeit('Kampf im Wasser'),
	noOpSonderfertigkeit('Kampfreflexe I-III'),
	noOpSonderfertigkeit('Kampfstil-Kombination'),
	noOpSonderfertigkeit('Kernschuss I-III'),
	noOpSonderfertigkeit('Kettenkugelkampf'),
	noOpSonderfertigkeit('Kha-Formation'),
	noOpSonderfertigkeit('Klinge drehen'),
	noOpSonderfertigkeit('Klingenfänger'),
	noOpSonderfertigkeit('Klingensturm'),
	noOpSonderfertigkeit('Klingentänzer'),
	noOpSonderfertigkeit('Kraftvoller Speerwurf'),
	noOpSonderfertigkeit('Kreuzblock'),
	noOpSonderfertigkeit('Lanzenangriff'),
	noOpSonderfertigkeit('Lanzenführung'),
	noOpSonderfertigkeit('Machtvolle Meisterparade'),
	noOpSonderfertigkeit('Meister der improvisierten Waffen'),
	noOpSonderfertigkeit('Meisterliche Geschossabwehr I-III'),
	noOpSonderfertigkeit('Meisterlicher Klingentänzer'),
	noOpSonderfertigkeit('Meisterliches Ausweichen'),
	noOpSonderfertigkeit('Meisterparade'),
	noOpSonderfertigkeit('Pikenwall'),
	noOpSonderfertigkeit('Plänkler-Formation'),
	noOpSonderfertigkeit('Präziser Schuss/Wurf I-III'),
	noOpSonderfertigkeit('Präziser Stich I-III'),
	noOpSonderfertigkeit('Querschuss I-III'),
	noOpSonderfertigkeit('Reißangriff'),
	noOpSonderfertigkeit('Riposte'),
	noOpSonderfertigkeit('Rundumschlag I-II'),
	noOpSonderfertigkeit('Scharfschütze I-II'),
	noOpSonderfertigkeit('Schildschlag'),
	noOpSonderfertigkeit('Schildspalter'),
	noOpSonderfertigkeit('Schildwall'),
	noOpSonderfertigkeit('Schnellladen (Kampftechnik)'),
	noOpSonderfertigkeit('Schnellziehen'),
	noOpSonderfertigkeit('Schwitzkasten'),
	noOpSonderfertigkeit('Spießgespann'),
	noOpSonderfertigkeit('Sturmangriff'),
	noOpSonderfertigkeit('Todesstoß'),
	noOpSonderfertigkeit('Turnierreiterei'),
	noOpSonderfertigkeit('Umrennen'),
	noOpSonderfertigkeit('Umwickeln'),
	noOpSonderfertigkeit('Ungeheuer-Taktik (einzelne Spezies)'),
	noOpSonderfertigkeit('Unterlaufen I-II'),
	noOpSonderfertigkeit('Unterwasserkampf'),
	noOpSonderfertigkeit('Verbessertes Ausweichen I-III'),
	noOpSonderfertigkeit('Verbessertes Unterlaufen'),
	noOpSonderfertigkeit('Verteidigungshaltung'),
	noOpSonderfertigkeit('Verteilter Eisenhagel'),
	noOpSonderfertigkeit('Vorstoß'),
	noOpSonderfertigkeit('Weitwurf'),
	noOpSonderfertigkeit('Wirbelangriff I-II'),
	noOpSonderfertigkeit('Wuchtschlag I-III'),
	noOpSonderfertigkeit('Wurf'),
	noOpSonderfertigkeit('Zu Fall bringen'),
	noOpSonderfertigkeit('Zweihändiger Reiterkampf'),
	noOpSonderfertigkeit('Adersin-Stil'),
	noOpSonderfertigkeit('Alter Adersin-Stil'),
	noOpSonderfertigkeit('Al’Drakorhim-Stil'),
	noOpSonderfertigkeit('Amazonen-Stil'),
	noOpSonderfertigkeit('Ardariten-Stil'),
	noOpSonderfertigkeit('Ayshara-Stil'),
	noOpSonderfertigkeit('Baburin-Stil'),
	noOpSonderfertigkeit('Balboram-Stil'),
	noOpSonderfertigkeit('Baliho-Stil'),
	noOpSonderfertigkeit('Bannstrahler-Stil'),
	noOpSonderfertigkeit('Beni Uchakâni-Stil'),
	noOpSonderfertigkeit('Bornländisches Raufen'),
	noOpSonderfertigkeit('Boxer-Stil'),
	noOpSonderfertigkeit('Cendrasch-Stil'),
	noOpSonderfertigkeit('Dajin-Stil'),
	noOpSonderfertigkeit('Distelritter-Stil'),
	noOpSonderfertigkeit('Ederion-Stil'),
	noOpSonderfertigkeit('Elenvina-Stil'),
	noOpSonderfertigkeit('Fasarer Blutgruben-Stil'),
	noOpSonderfertigkeit('Fedorino-Stil'),
	noOpSonderfertigkeit('Gardisten-Stil'),
	noOpSonderfertigkeit('Gareth-Stil'),
	noOpSonderfertigkeit('Garether Gossen-Stil'),
	noOpSonderfertigkeit('Gladiatoren-Stil'),
	noOpSonderfertigkeit('Golgariten-Stil'),
	noOpSonderfertigkeit('Hammerfaust-Stil'),
	noOpSonderfertigkeit('Hand Borons-Stil'),
	noOpSonderfertigkeit('Hardas-Stil'),
	noOpSonderfertigkeit('Havena-Stil'),
	noOpSonderfertigkeit('Hruruzat'),
	noOpSonderfertigkeit('Hylailos-Stil'),
	noOpSonderfertigkeit('Irbrasch-Stil'),
	noOpSonderfertigkeit('Ishannah al’Kira-Stil'),
	noOpSonderfertigkeit('Mantikor-Stil'),
	noOpSonderfertigkeit('Marwan Sahib-Stil'),
	noOpSonderfertigkeit('Mengbilla-Stil'),
	noOpSonderfertigkeit('Mercenario-Stil'),
	noOpSonderfertigkeit('Metessa Galora-Stil'),
	noOpSonderfertigkeit('Neersand-Stil'),
	noOpSonderfertigkeit('Odilmar-Stil'),
	noOpSonderfertigkeit('Pelleas-Stil'),
	noOpSonderfertigkeit('Phexcaer Gossen-Stil'),
	noOpSonderfertigkeit('Plänkler-Stil'),
	noOpSonderfertigkeit('Prem-Stil'),
	noOpSonderfertigkeit('Rabengarde-Stil'),
	noOpSonderfertigkeit('Rahjakavalier-Stil'),
	noOpSonderfertigkeit('Rhodenstein-Stil'),
	noOpSonderfertigkeit('Ritter des alten Wegs-Stil'),
	noOpSonderfertigkeit('Ritter des neuen Pfades-Stil'),
	noOpSonderfertigkeit('Rommilys-Stil'),
	noOpSonderfertigkeit('Rondras Schutz-Stil'),
	noOpSonderfertigkeit('Rondras Trutz-Stil'),
	noOpSonderfertigkeit('Sappeur-Stil'),
	noOpSonderfertigkeit('Sarvinio della Monte-Stil'),
	noOpSonderfertigkeit('Scanlail ni Uinin-Stil'),
	noOpSonderfertigkeit('Seekrieger-Stil'),
	noOpSonderfertigkeit('Seenritter-Stil'),
	noOpSonderfertigkeit('Seesoldaten-Stil'),
	noOpSonderfertigkeit('Sippenkrieger-Stil des Windhags'),
	noOpSonderfertigkeit('Sonnenlegion-Stil'),
	noOpSonderfertigkeit('Stammeskrieger-Stil'),
	noOpSonderfertigkeit('Tannhaus-Stil'),
	noOpSonderfertigkeit('Tarisharim-Stil'),
	noOpSonderfertigkeit('Thorwal-Stil'),
	noOpSonderfertigkeit('Unauer Schule'),
	noOpSonderfertigkeit('Valaria-Stil'),
	noOpSonderfertigkeit('Vinsalt-Stil'),
	noOpSonderfertigkeit('Waldritter-Stil'),
	noOpSonderfertigkeit('Winhall-Stil'),
	noOpSonderfertigkeit('Wulfgar-Stil'),
	noOpSonderfertigkeit('Xorlosch-Stil'),
	noOpSonderfertigkeit('Yppolitaner-Stil'),
	noOpSonderfertigkeit('Zyklopäisches Ringen'),
	noOpSonderfertigkeit('Backpfeifen-Sturm'),
	noOpSonderfertigkeit('Durch die Wand'),
	noOpSonderfertigkeit('Hose Herunterziehen/Hemd Hochziehen'),
	noOpSonderfertigkeit('Kneipen-Blutgrätsche'),
	noOpSonderfertigkeit('Kneipen-Geschossabwehr'),
	noOpSonderfertigkeit('Kneipen-Kopfstoß'),
	noOpSonderfertigkeit('Köpfe Aneinanderschlagen'),
	noOpSonderfertigkeit('Schlag auf den Kopf'),
	noOpSonderfertigkeit('Tür gegen den Kopf Knallen'),
	noOpSonderfertigkeit('Attacke verbessern'),
	noOpSonderfertigkeit('Ausweichen verbessern'),
	noOpSonderfertigkeit('Beistand der Götter I-II'),
	noOpSonderfertigkeit('Eigenschaft verbessern'),
	noOpSonderfertigkeit('Empathie'),
	noOpSonderfertigkeit('Erholsame Regeneration'),
	noOpSonderfertigkeit('Feenrettung'),
	noOpSonderfertigkeit('Fernkampf verbessern'),
	noOpSonderfertigkeit('Fleischwunde'),
	noOpSonderfertigkeit('Freund von Freunden'),
	noOpSonderfertigkeit('Gespür für das Böse'),
	noOpSonderfertigkeit('Haltet durch!'),
	noOpSonderfertigkeit('Heilkraft I-III'),
	noOpSonderfertigkeit('Höhere Prophezeiung'),
	noOpSonderfertigkeit('Letzte Reserve'),
	noOpSonderfertigkeit('Magiegespür'),
	noOpSonderfertigkeit('Parade verbessern'),
	noOpSonderfertigkeit('Prophezeiung'),
	noOpSonderfertigkeit('Schicksalsmacht'),
	noOpSonderfertigkeit('Wachsamkeit'),
	noOpSonderfertigkeit('Wink des Schicksals'),
	noOpSonderfertigkeit('Zeichen des Schicksals'),
	noOpSonderfertigkeit('Weg d. Adligen'),
	noOpSonderfertigkeit('Weg d. Apothekers'),
	noOpSonderfertigkeit('Weg d. Baderin'),
	noOpSonderfertigkeit('Weg d. Bardin'),
	noOpSonderfertigkeit('Weg d. Boten'),
	noOpSonderfertigkeit('Weg d. Fallenstellers'),
	noOpSonderfertigkeit('Weg d. Fleischers'),
	noOpSonderfertigkeit('Weg d. Gauklerin'),
	noOpSonderfertigkeit('Weg d. Gelehrten'),
	noOpSonderfertigkeit('Weg d. Heilerin'),
	noOpSonderfertigkeit('Weg d. Holzfällers'),
	noOpSonderfertigkeit('Weg d. Händlers'),
	noOpSonderfertigkeit('Weg d. Höflings'),
	noOpSonderfertigkeit('Weg d. Jägers'),
	noOpSonderfertigkeit('Weg d. Karawanenführerin'),
	noOpSonderfertigkeit('Weg d. Kontoristin'),
	noOpSonderfertigkeit('Weg d. Künstlerin'),
	noOpSonderfertigkeit('Weg d. Patrizierin'),
	noOpSonderfertigkeit('Weg d. Prospektors'),
	noOpSonderfertigkeit('Weg d. Prostituierten'),
	noOpSonderfertigkeit('Weg d. Räuberin'),
	noOpSonderfertigkeit('Weg d. Schankmagd'),
	noOpSonderfertigkeit('Weg d. Schaukämpferin'),
	noOpSonderfertigkeit('Weg d. Schreiberin'),
	noOpSonderfertigkeit('Weg d. Schriftstellers'),
	noOpSonderfertigkeit('Weg d. Seefahrerin'),
	noOpSonderfertigkeit('Weg d. Spitzelin'),
	noOpSonderfertigkeit('Weg d. Streuners'),
	noOpSonderfertigkeit('Weg d. Taschendiebes'),
	noOpSonderfertigkeit('Weg d. Tätowiererin'),
	noOpSonderfertigkeit('Weg d. Zimmermanns'),
	noOpSonderfertigkeit('Weg d. Zofe'),
	noOpSonderfertigkeit('Homunculusbindung'),
	noOpSonderfertigkeit('Angriff auf ungeschützte Stellen'),
	noOpSonderfertigkeit('Anspringen'),
	noOpSonderfertigkeit('Befreiungstritt'),
	noOpSonderfertigkeit('Corbetto'),
	noOpSonderfertigkeit('Flugangriff'),
	noOpSonderfertigkeit('Klammergriff'),
	noOpSonderfertigkeit('Mächtiger Schlag'),
	noOpSonderfertigkeit('Schwanz- oder Tentakelschwung'),
	noOpSonderfertigkeit('Trampeln'),
	noOpSonderfertigkeit('Unterwasserkampf'),
	noOpSonderfertigkeit('Verbeißen'),
	noOpSonderfertigkeit('Überrennen'),
	noOpSonderfertigkeit('Angriff auf ungeschützte Stellen'),
	noOpSonderfertigkeit('Angst riechen'),
	noOpSonderfertigkeit('Anspringen'),
	noOpSonderfertigkeit('Bewegungskünstler'),
	noOpSonderfertigkeit('Gesichter lesen'),
	noOpSonderfertigkeit('Gewohnheitstier'),
	noOpSonderfertigkeit('Rastullahs Schwingen'),
	noOpSonderfertigkeit('Schatzsucher'),
	noOpSonderfertigkeit('Schrecksicher'),
	noOpSonderfertigkeit('Schwächeninstinkt'),
	noOpSonderfertigkeit('Seefest'),
	noOpSonderfertigkeit('Stille Wacht'),
	noOpSonderfertigkeit('Trickser'),
	noOpSonderfertigkeit('Trittsicher (Geländetyp)'),
	noOpSonderfertigkeit('Unterwasserkampf'),
	noOpSonderfertigkeit('Warnsignal'),
	noOpSonderfertigkeit('Zusammenarbeit'),
	noOpSonderfertigkeit('Ablegen'),
	noOpSonderfertigkeit('Anzeigen'),
	noOpSonderfertigkeit('Apport'),
	noOpSonderfertigkeit('Aus'),
	noOpSonderfertigkeit('Fass I'),
	noOpSonderfertigkeit('Fass II'),
	noOpSonderfertigkeit('Fass III'),
	noOpSonderfertigkeit('Komm'),
	noOpSonderfertigkeit('Kunststück'),
	noOpSonderfertigkeit('Laut'),
	noOpSonderfertigkeit('Platz'),
	noOpSonderfertigkeit('Sitz'),
	noOpSonderfertigkeit('Still'),
	noOpSonderfertigkeit('Such'),
	noOpSonderfertigkeit('Treiben'),
	noOpSonderfertigkeit('Wache'),
	noOpSonderfertigkeit('Diebstahl'),
	noOpSonderfertigkeit('Dinge erspüren'),
	noOpSonderfertigkeit('Einschüchterndes Bellen'),
	noOpSonderfertigkeit('Erster unter Gleichen'),
	noOpSonderfertigkeit('Fluchbote'),
	noOpSonderfertigkeit('Furchtbote'),
	noOpSonderfertigkeit('Gaukeltricks'),
	noOpSonderfertigkeit('Gefährte in neuer Gestalt'),
	noOpSonderfertigkeit('Halluzinationsgift'),
	noOpSonderfertigkeit('Hexensinn'),
	noOpSonderfertigkeit('Hexenstimme'),
	noOpSonderfertigkeit('Hypnotischer Blick'),
	noOpSonderfertigkeit('Katzenplage'),
	noOpSonderfertigkeit('Kraftraub'),
	noOpSonderfertigkeit('Krötengift'),
	noOpSonderfertigkeit('Krötenschlag'),
	noOpSonderfertigkeit('Leben aufspüren'),
	noOpSonderfertigkeit('Nächtlicher Lebensraub'),
	noOpSonderfertigkeit('Schlafender Freund'),
	noOpSonderfertigkeit('Spinnensinn'),
	noOpSonderfertigkeit('Stimmungssinn'),
	noOpSonderfertigkeit('Streicheleinheiten'),
	noOpSonderfertigkeit('Tarnung'),
	noOpSonderfertigkeit('Teleportationsflug'),
	noOpSonderfertigkeit('Tiersinne'),
	noOpSonderfertigkeit('Ungesehener Beobachter'),
	noOpSonderfertigkeit('Wachsame Augen'),
	noOpSonderfertigkeit('Zwiegespräch'),
];

export { sonderfertigkeiten };

